config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/ayuda', to: 'pages#help', as: 'ayuda'
  resources :users, only: [:show, :index] do
    resources :appointments, only: [:new, :create]
    resources :reviews, only: [:show, :index]
    resources :profiles, only: [:show, :update]
  end

  resources :appointments, only: [:edit, :update, :index, :show] do
    resources :reviews, only: [:new, :create, :edit, :update]
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = Profile.find_by user_id: params[:user_id]
    @user = User.find(params[:user_id])
    authorize @user
  end

  def update
    @profile = Profile.find_by user_id: params[:user_id]
    if @profile.update(profile_params)
      @user = User.find(params[:user_id])
      authorize @user
      redirect_to user_path(@user)
    else
      render :new
    end
    # @profile.school = params[:profile][:school]
    # @profile.license_number = params[:profile][:license_number]
    # @profile.speciality = params[:profile][:speciality]
    # @profile.price = params[:profile][:price]
  end

  private

  def profile_params
    params.require(:profile).permit(:school, :license_number, :speciality, :price)
  end
end

app/views/profiles/show.html.erb
<h1>Datos personales</h1>

<%= simple_form_for(@user, url: registration_path(@user), html: { method: :patch }) do |t| %>
  <%= t.input :email, required: true, autofocus: true %>
  <%= t.input :first_name,
                required: false,
                input_html: { autocomplete: "new-first-name" } %>

  <%= t.input :last_name,
                required: false,
                input_html: { autocomplete: "new-last-name" } %>

  <%= t.input :dni,
                required: false,
                input_html: { autocomplete: "new-dni" } %>
  
  <%= t.input :address,
                required: false,
                input_html: { autocomplete: "new-address" } %>
  
  <%= t.input :cel_phone,
                required: false,
                input_html: { autocomplete: "new-cel_phone" } %>
  
  <%= t.input :password,
                hint: "leave it blank if you don't want to change it",
                required: false,
                input_html: { autocomplete: "new-password" } %>

  <%= t.input :password_confirmation,
                required: false,
                input_html: { autocomplete: "new-password" } %>
  <%= t.input :current_password,
                hint: "we need your current password to confirm your changes",
                required: true,
                input_html: { autocomplete: "current-password" } %>

  <%= t.submit %>
<% end %>

  <% if @user.professional %>

  <h1>Perfil Profesional</h1>

  <%= simple_form_for( @profile, url: user_profile_path(@user), html: { method: :patch }) do |t| %>
  <%= t.input :school,
                required: false,
                input_html: { autocomplete: "new-school" } %>

  <%= t.input :license_number,
                required: false,
                input_html: { autocomplete: "new-license-number" } %>

  <%= t.input :speciality,
                required: false,
                input_html: { autocomplete: "new-speciality" } %>
  
  <%= t.input :price,
                required: false,
                input_html: { autocomplete: "new-price" } %>
  <%= t.submit %>
  <% end %>
<% end %>