config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/ayuda', to: 'pages#help', as: 'ayuda'
  resources :users, only: [:show, :index] do
    resources :appointments, only: [:new, :create]
    resources :reviews, only: [:show, :index]
    resources :profiles, only: [:show, :update]
  end

  resources :appointments, only: [:edit, :update, :index, :show] do
    resources :reviews, only: [:new, :create, :edit, :update]
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :appointments, foreign_key: :client_id
  has_many :reservations, foreign_key: :professional_id, class_name: "Appointment"
  has_many :reviews, through: :reservations
  after_create :create_profile
  has_one_attached :photo
  has_one :profile
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def create_profile
    profile = Profile.new(user_id: id)
    profile.save
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def show
    @user = User.find(params[:id])
    if @user.professional
    @profile = Profile.find_by user_id: params[:id]
    @appointment = Appointment.new
    #@users_coo = User.geocoded # returns flats with coordinates
    @marker =
      [{
        lat: @user.latitude,
        lng: @user.longitude
      }]
    else
      authorize @user
      redirect_to root_path
    end
    authorize @user
  end

  def index
    @users = []
    if !params.nil?
      # Ejecuto el query con los filtros
      @profiles = query_builder(params)
      if @profiles.present?
        @users = policy_scope(User.where(id: @profiles.pluck(:user_id))).order(created_at: :desc)
      else
        @users = policy_scope(User.where(professional: true)).order(created_at: :desc)
      end
    else
      @users = policy_scope(User.where(professional: true)).order(created_at: :desc)
    end
    @users_coo = User.geocoded # returns flats with coordinates
    @markers = @users_coo.map do |users_coo|
      {
        lat: users_coo.latitude,
        lng: users_coo.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { users_coo: users_coo })
      }
    end
    @users
  end

  def query_builder(param)
    school = param[:school].presence
    speciality = param[:speciality].presence
    if school && speciality
      @profiles = Profile.where("school LIKE ? AND speciality LIKE ?", school, speciality)
    elsif speciality
      @profiles = Profile.where("speciality LIKE ?", speciality)
    elsif school
      @profiles = Profile.where("school LIKE ?", school)
    else
      @profiles = nil
    end
    @profiles
  end
end

app/views/users/_info_window.html.erb
<div class="p-2">
    <h3><%= users_coo.first_name %> <%= users_coo.last_name %></h3>
    <p>Especialidad: <%= Profile.find(users_coo.id).speciality %></p>
    <p>Precio por sesion <strong><%= Profile.find(users_coo.id).price %>$</strong></p>
</div>

app/views/users/index.html.erb
<div class='navbar-lewagon'>
<%= content_for(:navbar_class, "navbar-home") %>
</div>
<form class="simple_form user m-3" action="/users" method="get">
  <div class="input string required user_name">
    <label class="string required" for="user_name">Escuela</label>
    <input class="string required" type="text" name="school" id="school_keys" />
    <label class="string required" for="user_name">Especialidad</label>
    <input class="string required" type="text" name="speciality" id="school_keys" />
    <input type="submit" value="Filtrar" class="btn btn-success">
  </div>
</form>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
      <%@users.each do |psico|%>
          <%= link_to user_path(psico.id),{:style=>'text-decoration:none;', :class => "one"} do %>
          <div class="card-product d-flex flex-row m-4">
            <div class="card-product-photo">
              <%= cl_image_tag psico.photo.key %>
            </div>
            <div class="card-product-body flex-grow-1 ">
              <h2><%=psico.first_name%> <%=psico.last_name%></h2>
              <p>Especialidad en <%= Profile.find(psico.id).speciality %></p>
              <p>Escuela de pensamiento <%= Profile.find(psico.id).school %></p>
              <h5>Contacto <%=psico.cel_phone%></h5>
            </div>
            <div class="card-product-info flex-shrink-1 align-self-end ">
              <div class="d-flex flex-column align-items-end ">
                <% if psico.reviews.count > 0  %>
                <p>Rating: <%= psico.reviews.average(:rating_sharp).round(1) %> ⭐ (<%= psico.reviews.count %>) </p>
                <% end %>
                <p>Precio por sesion <strong><%= Profile.find(psico.id).price %>$</strong></p>
              </div>
            </div>
          </div>
          <%end%>
      <%end%>
    </div>
    <div class="col-md-6 d-none d-md-block ">
      <div class="sticky-top">
        <div id="map"
            style="width: 100%; height: 600px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="banner-map">
  <div id="map" class="col"
    style="width: 100%; height: 200px; objet_fit: cover ;"
    data-markers="<%= @marker.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>
<div class="">
  <div class="m-3 ">
    <div class="row">
      <div class="col-7 row m-3 flash ">
        <h1>Informacion del profesional:  <%=@user.first_name.capitalize%></h1> 
        <div class="col-4">
          <br>
          <% if policy(@user.profile).show? %>
          <% link_to "Editar perfil profesional", user_profile_path(@user) %>
          <% end %>
          <%= cl_image_tag @user.photo.key, class: "avatar-square" %>
          <br>
          <p> </p>
        </div>
        <div class="col-8">
          <ul class="list-group list-group-flush ">
            <li class="list-group-item border-bottom-0"><h3>Nombre: <%=@user.first_name.capitalize%> </h3>
            <li class="list-group-item"><h3>Apellido <%=@user.last_name.capitalize%></li></h3>
            <li class="list-group-item">Escuela de pensamiento: <%=@user.profile.school%></li>
            <li class="list-group-item">Especialidad: <%=@user.profile.speciality%></li>
            <li class="list-group-item">Nro de Matricula: <%=@user.profile.license_number%></li>
            <li class="list-group-item">Precio: $ <%=@user.profile.price%>.00</li>
             <% if current_user.present? %>
              <li class="list-group-item">Domicilio: <%=@user.address%></li>
            <% end %>
            <li class="list-group-item">Rating: <%= @user.reviews.average(:rating_sharp).round(1) %> ⭐ (<%= @user.reviews.count %>)</li>
          </ul>
        </div>
        <div class="container">
          <%= link_to "Volver", users_path, class:'btn btn-secondary' %>
        </div>
      </div>
      <% if current_user.present? %>
      <div class="col-4" style="border: 1px solid rgb(221, 221, 221); border-radius: 12px; padding: 24px; box-shadow: rgba(0, 0, 0, 0.12) 0px 6px 16px;">
        <h1> Reserva tu cita: <h1>
        <%= simple_form_for([@user, @appointment]) do |f| %> 
            <%= f.input :appointment_date, label: "Elija el dia", wrapper_html: { class: 'flex-select' }, as: :date, html5: true %>   
            <!-- deplegable de horios-->
            <%= f.input :start_hour, collection: (9..20).to_a, label: "Elija el horario"  %>
            <% puts f.input :appointment_date %>
            <%= f.submit class:'btn btn-success' %>
          <% end %>
        <%= link_to "Lista de citas", appointments_path, class:"btn btn-dark" , style: 'display:fixed;' %>
      </div>

      <%else%>
      <div class="col-4 my-5">
        <%= link_to "Login para reservar!", new_user_session_path, class:'btn btn-success' %>
        <%= link_to "Volver", users_path, class:'btn btn-secondary' %>
      <%end%>
      </div>
    </div>
  </div>
</div>